# Based on: https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/interactive_rendering.py
"""
Use this script to interactively play RWARE

You can control the interaction with the following keys:
- Up Arrow keys: move current agent forward
- Left/ Right Arrow keys: rotate current agent left/ right
- P/ L: pickup/ drop shelf
- SPACE: do nothing
- TAB: change the current agent
- R: reset the environment
- H: show help
- D: display agent info (per step)
- ESC: exit
"""
from argparse import ArgumentParser
from pathlib import Path
import json
import warnings

import numpy as np
import gymnasium as gym

from rware.warehouse import Action, ObservationType, RewardType, ImageLayer


def parse_args():
    parser = ArgumentParser()
    parser.add_argument(
        "--env",
        type=str,
        default="rware-tiny-2ag-v2",
        help="Environment to use",
    )
    parser.add_argument(
        "--max_steps",
        type=int,
        default=None,
        help="Maximum number of steps per episode (<=0 disables).",
    )
    parser.add_argument(
        "--env-config",
        type=str,
        default=None,
        help="Path to a JSON env config generated by the launcher.",
    )
    parser.add_argument(
        "--layout",
        type=str,
        default=None,
        help="Custom layout string (rows separated by newlines)",
    )
    parser.add_argument(
        "--layout-file",
        type=str,
        default=None,
        help="Path to a layout text file",
    )
    parser.add_argument("--shelf_rows", type=int, default=None)
    parser.add_argument("--shelf_columns", type=int, default=None)
    parser.add_argument("--column_height", type=int, default=None)
    parser.add_argument("--n_agents", type=int, default=None)
    parser.add_argument("--msg_bits", type=int, default=None)
    parser.add_argument("--sensor_range", type=int, default=None)
    parser.add_argument("--request_queue_size", type=int, default=None)
    parser.add_argument("--max_inactivity_steps", type=int, default=None)
    parser.add_argument("--reward_type", type=str, default=None)
    parser.add_argument("--observation_type", type=str, default=None)
    parser.add_argument("--normalised_coordinates", action="store_true")
    parser.add_argument(
        "--display_info",
        action="store_true",
        help="Display agent info per step",
    )
    return parser.parse_args()


def _parse_reward_type(value: str):
    if value is None:
        return None
    value = value.strip().upper()
    if "." in value:
        value = value.split(".")[-1]
    if value == "INDIVIDUAL":
        return RewardType.INDIVIDUAL
    if value == "GLOBAL":
        return RewardType.GLOBAL
    if value in ("TWO_STAGE", "TWOSTAGE"):
        return RewardType.TWO_STAGE
    raise ValueError(f"Unknown reward type: {value}")


def _parse_observation_type(value: str):
    if value is None:
        return None
    value = value.strip().upper()
    if "." in value:
        value = value.split(".")[-1]
    if value == "FLATTENED":
        return ObservationType.FLATTENED
    if value == "IMAGE":
        return ObservationType.IMAGE
    if value in ("IMAGE_DICT", "IMAGEDICT"):
        return ObservationType.IMAGE_DICT
    raise ValueError(f"Unknown observation type: {value}")


def _parse_image_layer(value):
    if isinstance(value, ImageLayer):
        return value
    if isinstance(value, int):
        return ImageLayer(value)
    name = str(value).strip()
    if "." in name:
        name = name.split(".")[-1]
    name = name.upper()
    try:
        return ImageLayer[name]
    except KeyError as exc:
        raise ValueError(f"Unknown image layer: {value}") from exc


def _resolve_env_config(env_id, env_config_path):
    if not env_config_path:
        return env_id, {}
    path = Path(env_config_path).expanduser()
    if not path.exists():
        raise FileNotFoundError(f"Env config not found: {path}")
    data = json.loads(path.read_text())
    config_env_id = data.get("env_id") or env_id
    kwargs = data.get("kwargs") or {}
    if not isinstance(kwargs, dict):
        raise ValueError("Env config 'kwargs' must be a dict")
    kwargs = {k: v for k, v in kwargs.items() if v is not None}
    # The copied launcher can emit traffic-wrapper metadata keys from the upstream project.
    # Local human-play instantiates the raw RWARE env directly, so strip wrapper-only keys.
    kwargs = {
        k: v
        for k, v in kwargs.items()
        if not (
            k.startswith("traffic_")
            or k
            in {
                "env_config",
                "wrappers",
                "time_limit",
                "reward_scheme",
                "hard_deadlock_stall_steps",
                "deadlock_hard_stall_steps",
                "deadlock_soft_stall_steps",
                "reward_pickup_correct",
                "reward_pickup_wrong",
                "reward_drop_correct",
                "reward_drop_wrong",
                "conflict_shaping_enabled",
                "conflict_shaping_lambda_swap",
                "conflict_shaping_lambda_vtx",
                "conflict_shaping_lambda_block_agent",
                "conflict_shaping_lambda_step",
                "conflict_shaping_lambda_deadlock",
                "conflict_shaping_lambda_break",
                "conflict_shaping_break_window",
            }
        )
    }
    if "reward_type" in kwargs:
        kwargs["reward_type"] = _parse_reward_type(kwargs["reward_type"])
    if "observation_type" in kwargs:
        kwargs["observation_type"] = _parse_observation_type(kwargs["observation_type"])
    if "image_observation_layers" in kwargs and kwargs["image_observation_layers"] is not None:
        layers = kwargs["image_observation_layers"]
        if not isinstance(layers, (list, tuple)):
            raise ValueError("image_observation_layers must be a list")
        kwargs["image_observation_layers"] = [_parse_image_layer(layer) for layer in layers]
    return config_env_id, kwargs


class InteractiveRWAREEnv:
    """Use this script to interactively play RWARE"""

    def __init__(
        self,
        env: str,
        display_info: bool = True,
        env_kwargs=None,
    ):
        env_kwargs = env_kwargs or {}
        self.env = gym.make(env, render_mode="human", **env_kwargs)
        self.n_agents = self.env.unwrapped.n_agents
        self.running = True
        self.current_agent_index = 0
        self.current_action = None

        self.t = 0
        self.ep_returns = np.zeros(self.n_agents)
        self.reset = False

        self.display_info = display_info

        obss, _ = self.env.reset()
        self.env.render()
        self.env.unwrapped.renderer.window.on_key_press = self._key_press

        if self.display_info:
            self._display_info(obss, [0] * self.n_agents, False)

        self._cycle()

    def _help(self):
        print("Use the up arrow key to move the current agent forward")
        print("Use the left/ right arrow keys to rotate the current agent left/ right")
        print("Press P or L to pickup/ drop shelf")
        print("Use the SPACE key to do nothing")
        print("Press TAB to change the current agent")
        print("Press R to reset the environment")
        print("Press H to show help")
        print("Press D to display agent info")
        print("Press ESC to exit")
        print()

    def _format_pos(self, pos):
        return f"row {pos[0] + 1}, col {pos[1] + 1}"

    def _get_current_agent_info(self):
        agent_carrying = self.env.unwrapped.agents[self.current_agent_index].carrying_shelf
        agent_x = self.env.unwrapped.agents[self.current_agent_index].x
        agent_y = self.env.unwrapped.agents[self.current_agent_index].y
        agent_str = f"Agent {self.current_agent_index + 1} (at row {agent_y + 1}, col {agent_x + 1}"
        if agent_carrying:
            agent_str += ", carrying shelf)"
        else:
            agent_str += ")"
        return agent_str
        

    def _display_info(self, obss, rews, done):
        print(f"Step {self.t}:")
        print(f"\tSelected: {self._get_current_agent_info()}")
        print(f"\tObs: {obss[self.current_agent_index]}")
        print(f"\tRew: {round(rews[self.current_agent_index], 3)}")
        print(f"\tDone: {done}")
        print()

    def _increment_current_agent_index(self, index: int):
        index += 1
        if index == self.n_agents:
            index = 0
        return index

    def _key_press(self, k, mod):
        from pyglet.window import key

        if k == key.LEFT:
            self.current_action = Action.LEFT
        elif k == key.RIGHT:
            self.current_action = Action.RIGHT
        elif k == key.UP:
            self.current_action = Action.FORWARD
        elif k == key.P or k == key.L:
            self.current_action = Action.TOGGLE_LOAD
        elif k == key.SPACE:
            self.current_action = Action.NOOP
        elif k == key.TAB:
            self.current_action = None
            self.current_agent_index = self._increment_current_agent_index(
                self.current_agent_index
            )
            if self.display_info:
                print(f"Now selected: {self._get_current_agent_info()}")
        elif k == key.R:
            self.current_action = None
            self.reset = True
        elif k == key.H:
            self.current_action = None
            self._help()
        elif k == key.D:
            self.current_action = None
            self.display_info = not self.display_info
        elif k == key.ESCAPE:
            self.running = False
        else:
            self.current_action = None
            warnings.warn(f"Key {k} not recognized")

    def _cycle(self):
        while self.running:
            if self.reset:
                if self.display_info:
                    print(f"Finished episode with episodic returns: {[round(ret, 3) for ret in self.ep_returns]}")
                    print()
                obss, _ = self.env.reset()
                self.reset = False
                self.ep_returns = np.zeros(self.n_agents)
                self.t = 0

                if self.display_info:
                    self._display_info(obss, [0] * self.n_agents, False)

            should_step = self.current_action is not None
            if should_step:
                actions = [Action.NOOP] * self.n_agents
                actions[self.current_agent_index] = self.current_action
                actions = [act.value for act in actions]
                obss, rews, done, trunc, _ = self.env.step(actions)
                self.ep_returns += np.array(rews)
                self.t += 1

                if self.display_info:
                    self._display_info(obss, rews, done or trunc)

                if done or trunc:
                    self.reset = True

                self.current_action = None
            self.env.render()
        self.env.close()



if __name__ == "__main__":
    args = parse_args()
    try:
        reward_type = _parse_reward_type(args.reward_type)
        observation_type = _parse_observation_type(args.observation_type)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc

    try:
        env_name, env_kwargs = _resolve_env_config(args.env, args.env_config)
    except (ValueError, FileNotFoundError, json.JSONDecodeError) as exc:
        raise SystemExit(str(exc)) from exc

    layout_text = None
    if args.layout_file:
        layout_text = Path(args.layout_file).read_text()
    elif args.layout:
        layout_text = args.layout

    env_kwargs = env_kwargs or {}
    if layout_text:
        env_kwargs["layout"] = layout_text
    if args.shelf_rows is not None:
        env_kwargs["shelf_rows"] = args.shelf_rows
    if args.shelf_columns is not None:
        env_kwargs["shelf_columns"] = args.shelf_columns
    if args.column_height is not None:
        env_kwargs["column_height"] = args.column_height
    if args.n_agents is not None:
        env_kwargs["n_agents"] = args.n_agents
    if args.msg_bits is not None:
        env_kwargs["msg_bits"] = args.msg_bits
    if args.sensor_range is not None:
        env_kwargs["sensor_range"] = args.sensor_range
    if args.request_queue_size is not None:
        env_kwargs["request_queue_size"] = args.request_queue_size
    if args.max_inactivity_steps is not None:
        env_kwargs["max_inactivity_steps"] = (
            None if args.max_inactivity_steps <= 0 else args.max_inactivity_steps
        )
    if args.max_steps is not None:
        env_kwargs["max_steps"] = None if args.max_steps <= 0 else args.max_steps
    if reward_type is not None:
        env_kwargs["reward_type"] = reward_type
    if observation_type is not None:
        env_kwargs["observation_type"] = observation_type
    if args.normalised_coordinates:
        env_kwargs["normalised_coordinates"] = True

    InteractiveRWAREEnv(
        env=env_name,
        display_info=args.display_info,
        env_kwargs=env_kwargs,
    )
